# Generated by Django 4.2 on 2023-05-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField(default='', max_length=500)),
            ],
        ),
    ]
