# Generated by Django 4.2 on 2023-05-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='img',
            field=models.TextField(),
        ),
    ]
