# Generated by Django 4.2 on 2023-05-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='img',
            field=models.CharField(max_length=50),
        ),
    ]
